### ISSUE TITLE
Downloading the JSON response

### ISSUE THREAD

**Issue by jbehrens94** [cloudcreativity/demo-laravel-json-api#1]
When I tried to execute my JSON endpoint it automatically sent a response to my browser (Safari) telling it to download the response to hard drive. How does this work? I just want to view the response in my browser.

**Comment by lindyhopchris** [comment]
Hi! I don't know how that works off the top of my head. I'm using Ubuntu/Chrome and it shows in my browser without downloading.

The response will be sending a `Content-Type: application/vnd.api+json` header so your browser must be interpreting that as something you need to download. I.e. it'll be a browser thing. Would be interested to hear if you figure it out!

**Comment by jbehrens94** [comment]
Hi!

If I change the headers to send `Content-Type: application/json` it just works well.
I use Safari on macOS 10.12 Sierra, in case that helps you.

Must be some quirk Safari has, I suppose.

**Comment by chriscalip** [comment]
Error sighted. In my case changing config/json-api-v1.php codecs['encoders'] and codes['decoders'] does not change the output from `Content-Type: application/vnd.api+json` to `Content-Type: application/json`
hence I keep getting headers `Content-Type: application/vnd.api+json`. I am using ubuntu 16.04 firefox and it kept prompting me to download. I then made use of firefox plugin jsonviewer to map application/vdn.api+json as application/json

**Comment by lindyhopchris** [comment]
@chriscalip thanks for reporting this - confirmed this is a bug in the latest version. Fix looks simple but need to investigate further.
