### ISSUE TITLE
How do I let this ".../api/v1/posts?slug=iure-cupiditate-quia-ratione-alias" work?

### ISSUE THREAD

**Issue by ericgaonz** [cloudcreativity/demo-laravel-json-api#10]
Anyone know how to let the URL below work?
.../api/v1/posts?slug=iure-cupiditate-quia-ratione-alias

**Comment by ericgaonz** [comment]
Or is there any other way which we can do the search by the slug?

**Comment by lindyhopchris** [comment]
Hi! Use this:

/api/v1/posts?filter[slug]=iure-cupiditate-quia-ratione-alias

As per this in the spec:
http://jsonapi.org/format/#fetching-filtering

**Comment by ericgaonz** [comment]
Thank you so much.
