### ISSUE TITLE
the "self" link is wrong, it missed the alias value which I set in vhost config file.

### ISSUE THREAD

**Issue by ericgaonz** [cloudcreativity/demo-laravel-json-api#11]
My GET request URL:
https://192.168.99.100/services/test/api/v1/posts/1

My response result:
{
    "data": {
        "type": "posts",
        "id": "1",
        "attributes": {
            "title": "XXX",
            "slug": "XXX",
            "content": "XXX",
        },
        "links": {
            "self": "https://192.168.99.100/api/v1/posts/1"
        }
    }
}

So the "self" which missed the "/services/test", please help me to work it out, many thx.

**Comment by lindyhopchris** [comment]
You need to update the URL prefix in your API config:

https://github.com/cloudcreativity/demo-laravel-json-api/blob/5.5/config/json-api-v1.php#L80

**Comment by ericgaonz** [comment]
@lindyhopchris Thx for your response. I fixed it by resetting my Apache host config file.
