### ISSUE TITLE
How to consume internal Api

### ISSUE THREAD

**Issue by ngkarkeong** [cloudcreativity/demo-laravel-json-api#12]
Hi Christopher ,
I am trying to consume my own api. I try to use the code

On Blade
         @jsonapi('v1', JSON_PRETTY_PRINT)
         <script type="application/vnd.api+json">
            @encode($spots)
        </script>

On Router
        $guzzleClient = new GuzzleHttp\Client(['base_uri' => 'http://localhost/api/']);
        $client = json_api('v1')->client($guzzleClient);
        $response = $client->index('v1/spots');
    
        var_dump($response->getDocument()->getResources());
        return view('spot', ["spots" => $response]);

And i get the this error. 

ErrorException (E_ERROR)
Schema is not registered for a resource at path ''. (View: C:\wamp64\www\balispots\resources\views\spot.blade.php)

what would you suggest it could be? or do you have an example how to achieve this?
thanks.

**Comment by lindyhopchris** [comment]
Hi!

To encode resources into a Blade template, you don't need to use Guzzle to fire a request at your own API.

All you need to do is get the objects from the database (or wherever they are stored an pass) and pass them into your template.

E.g. for Eloquent, in your router:

```php
$spots = Spot::all();
```

(or whatever Eloquent query you need to do)

**Comment by ngkarkeong** [comment]
thank for the quick reply. 
It is great, it worked for the decoding part, it's a big help.
However, in certain situation i have  to consume my own Json-Api.
So, i would need to to be able to serialize the resources [object] to json resources. 
what would suggest in that case?
cheers.

**Comment by lindyhopchris** [comment]
the client doesn't convert the responses into the actual application objects. So to dump it to JSON in your template you'd just need to use `json_serialize` on the `$response->getDocument()` and that would output the JSON API payload.

**Comment by ngkarkeong** [comment]
That work:).
I am trying to push it a a bit further. i tried to consume the controller directly instead of using the cURL.
however, i have no idea how to initial the EloquentController because it is dynamic binded to Hydrator, which i have completely no idea where i can find in the source code (i guess). where can i look at if i want to call EloquentController from another controller?
I am so sorry, i am absolutely in Github community, i know this hardly consider issue at all. Is there any other place i can ask this kind of question?

**Comment by lindyhopchris** [comment]
If you want to build anything in Laravel like that, just do `$controller = app(MyController::class)` and it will take care of injecting all the dependencies for you.
