### ISSUE TITLE
Example of POSTing via jsonapi needed

### ISSUE THREAD

**Issue by xitude** [cloudcreativity/demo-laravel-json-api#16]
I've been learning [jsonapi](https://github.com/cloudcreativity/laravel-json-api) from this example project. Something I'm unable to figure out is how to POST via Postman to insert rows.

I'm sure if you added this to the example it would help people like myself understand the way to do it inline with the jsonapi standard.

Cheers.

**Comment by lindyhopchris** [comment]
Hi! So you should be able to POST something as long as you set up the following request via Postman:

```html
POST /api/v1/posts HTTP/1.1
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json

{
  "data": {
    "type": "posts",
    "attributes": {
      "title": "My First Post",
      "content": "...",
      "slug": "my-first-post",
      "published-at": null
    },
    "relationships": {
      "author": {
        "data": { "type": "people", "id": "1" }
      }
    }
  }
}
```

I don't use Postman so can't provided any specific advice as to how to set up this HTTP request in that.

Does that help?
