### ISSUE TITLE
create relationship resource

### ISSUE THREAD

**Issue by ehsan5** [cloudcreativity/demo-laravel-json-api#18]
Hello,I want two create with eachother, for example I want care post and its tag with eachother,Can you help me by show the examples?

**Comment by lindyhopchris** [comment]
Hey! Do you mean that you want to support a `POST /posts/1/relationships/tags` request as per this part of the spec:
http://jsonapi.org/format/#crud-updating-to-many-relationships

**Comment by ehsan5** [comment]
No I want create post and tag with one request
