### ISSUE TITLE
Show null reltionship

### ISSUE THREAD

**Issue by Robindfuller** [cloudcreativity/demo-laravel-json-api#19]
I don't see anywhere showing how to specify that a relationship does not exists. Is this possible?

example:

    "user": {
                    "data": {},
                    "links": {
                        "related": ...
                    }
                },

I just seem to get

    "user": {                    
                    "links": {
                        "related": ...
                    }
                },

**Comment by lindyhopchris** [comment]
Hey! Yes your schema would have to return a `null` data value:

```php
    public function getRelationships($resource, $isPrimary, array $includeRelationships)
    {
        return [
            'user' => [
                self::SHOW_SELF => true,
                self::SHOW_RELATED => true,
                self::DATA => null,
            ],
        ];
    }
```

**Comment by Robindfuller** [comment]
Hi thanks for the reply. 

That was what I initially tried. However the generated JSON does not contain a "data" attribute at all. I would have hoped that it would generate....

    ...
    "user": {
        "data": null,
        "links": {
            "self": "http://127.0.0.1:8000/api/v1/things/6/relationships/user",
            "related": "http://127.0.0.1:8000/api/v1/things/6/user"
        }
    },
    ...

but instead using `self::DATA => null` in my schema removes the data attribute entirely...

    ...
    "user": {
        "links": {
            "self": "http://127.0.0.1:8000/api/v1/things/6/relationships/user",
            "related": "http://127.0.0.1:8000/api/v1/things/6/user"
        }
    },
    ...

The problem is, that my frontend application must request the related URL just to find out that it's null. Ok for one record but when I have a list of hundreds, it causes hundreds of requests. That's why I'm using ?include in the first place.

Any ideas?

**Comment by Robindfuller** [comment]
Thank you!

**Comment by Robindfuller** [comment]
Thank you!
