### ISSUE TITLE
Add default error description to InvalidJsonException 

### ISSUE THREAD

**Issue by Nizari** [cloudcreativity/demo-laravel-json-api#20]
If you have invalid json, you know only get a 400 returned. It would be great if it also gives a default title and description regarding the error for easier debugging purposes.
Either in `config/json-api-errors.php` or in the `app/Exception/handler.php`

**Comment by lindyhopchris** [comment]
Hi! Yes, that definitely needs doing. I've created an issue in the `laravel-json-api` package for it, so will close this issue here.
