### ISSUE TITLE
How do is add the validator rules for the sub attributes?

### ISSUE THREAD

**Issue by ericgaonz** [cloudcreativity/demo-laravel-json-api#23]
The rules of first-name & last-name are working fine, but I don't know how do I add rules for account/bank-d and account/account-number.

**The attribute rules codes:**
return [
            'first-name' => "$required|string|between:1,45",
            'last-name' => "$required|string|between:1,45",
            'account.bank-id' => "$required|integer|between:1,10",
            'account/account-number' => "$required|string|between:1,45"
        ];

**The request body:**
{
    "data": {
        "type": "beneficiaries",
        "attributes": {
            "first-name": "Qi",
            "last-name": "Li",
            "account": {
              "bank-id": "1487",
              "account-number": "4511133463136"
            }
        }
    }
}

**Comment by ericgaonz** [comment]
but it doesn't work for me.

**Comment by lindyhopchris** [comment]
I think your issue might be that `"1487"` will actually pass the integer rule. So the above example that you posted has valid data. Definitely worth submitting `bank-id` as `foo` to see if that fails as that will test my theory!!

**Comment by ericgaonz** [comment]
First thx for your help, I got another one about how do I add a validator for the decimal attributes?
I want to get a decimal number to two decimal places and the min number is 5.00.
'send-amount' => "$required|decimals|Min:5.00"

**Comment by lindyhopchris** [comment]
You'll probably need to write your own rule for that
https://laravel.com/docs/5.6/validation#custom-validation-rules

**Comment by ericgaonz** [comment]
Will try it, thx so much.
