### ISSUE TITLE
Demo site uses PHP 7.1 nullable types feature despite > v5.6.4 decalaration

### ISSUE THREAD

**Issue by SirLamer** [cloudcreativity/demo-laravel-json-api#3]
Per the subject...

There is a nullable return type declaration here:
https://github.com/cloudcreativity/demo-laravel-json-api/blob/5.4/app/SiteRepository.php#L35
There may be others but I haven't gone looking.

This is supported only in PHP 7.1.

in composer.json it says that the package runs on PHP 5.6.4 or greater, same as Laravel 5.4.

I suggest that you stick to, at most, PHP 7.0 syntax and avoid 7.1 for now, since it was just recently released and is not a requirement for Laravel. I believe Laravel 5.5 will require PHP 7.0, though.

**Comment by SirLamer** [comment]
I submitted at a PR. Your call!
https://github.com/cloudcreativity/demo-laravel-json-api/pull/5

**Comment by lindyhopchris** [comment]
Not so sure about this. The demo is meant to be run in Homestead, which has PHP 7.1. I probably need to change the `composer.json` PHP requirement.

Let me have a think!

**Comment by SirLamer** [comment]
Well, okay then, though many people including myself are working on an existing Homestead environment with PHP 7.0. Your call, though.

**Comment by lindyhopchris** [comment]
Ok, good point. I'll remove the 7.1 requirement but will set to 7.0
